package UI;

import Autenticacion.Session;
import Modelos.Usuario;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public final class Dashboard extends javax.swing.JFrame {

    // ENUM ROLES
    enum MODO {
        ADMIN, USER, NOTHING
    }

    MODO modo;

    public Dashboard() throws SQLException {

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        modo = MODO.NOTHING;
        ocultarBotonesDeterminados();

//        try {
//            // Prueba conexion
//            DBConexion.getConnection();
//            JOptionPane.showMessageDialog(null, "Conexion correcta");
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Error al conectar");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        bg = new javax.swing.JPanel();
        elimClienteBtn = new javax.swing.JButton();
        abrirCuentaBtn = new javax.swing.JButton();
        cerrarCuentaBtn = new javax.swing.JButton();
        depositarBtn = new javax.swing.JButton();
        retirarBtn = new javax.swing.JButton();
        transBtn = new javax.swing.JButton();
        consultaBtn = new javax.swing.JButton();
        buscarClienteBtn = new javax.swing.JButton();
        LABEL_MENU = new javax.swing.JLabel();
        contenidoPanel = new javax.swing.JPanel();
        inAdminBtn = new javax.swing.JButton();
        InClienteBtn = new javax.swing.JButton();
        registrarseBtn = new javax.swing.JButton();
        histTransaccionesBtn = new javax.swing.JButton();
        cerrarSesionBtn = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        inicio_btn = new javax.swing.JMenuItem();
        salir_btn = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(0, 102, 204));

        elimClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elimClienteBtn.setText("Eliminar cliente");
        elimClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimClienteBtnActionPerformed(evt);
            }
        });

        abrirCuentaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abrirCuentaBtn.setText("Abrir cuenta");
        abrirCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCuentaBtnActionPerformed(evt);
            }
        });

        cerrarCuentaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarCuentaBtn.setText("Cerrar cuenta");
        cerrarCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarCuentaBtnActionPerformed(evt);
            }
        });

        depositarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositarBtn.setText("Depositar");
        depositarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarBtnActionPerformed(evt);
            }
        });

        retirarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retirarBtn.setText("Retirar");
        retirarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBtnActionPerformed(evt);
            }
        });

        transBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transBtn.setText("Transferir");
        transBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transBtnActionPerformed(evt);
            }
        });

        consultaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consultaBtn.setText("Consultar saldos");
        consultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBtnActionPerformed(evt);
            }
        });

        buscarClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarClienteBtn.setText("Buscar cliente");
        buscarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteBtnActionPerformed(evt);
            }
        });

        LABEL_MENU.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LABEL_MENU.setForeground(new java.awt.Color(255, 255, 255));
        LABEL_MENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABEL_MENU.setText("B A N C O");

        inAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inAdminBtn.setText("INICIAR COMO ADMINISTRADOR");
        inAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inAdminBtnActionPerformed(evt);
            }
        });

        InClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InClienteBtn.setText("INICIAR SESION");
        InClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InClienteBtnActionPerformed(evt);
            }
        });

        registrarseBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoPanelLayout = new javax.swing.GroupLayout(contenidoPanel);
        contenidoPanel.setLayout(contenidoPanelLayout);
        contenidoPanelLayout.setHorizontalGroup(
            contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPanelLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrarseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InClienteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inAdminBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addGap(341, 341, 341))
        );
        contenidoPanelLayout.setVerticalGroup(
            contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(InClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(inAdminBtn)
                .addGap(58, 58, 58))
        );

        histTransaccionesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        histTransaccionesBtn.setText("Ver Transacciones");
        histTransaccionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histTransaccionesBtnActionPerformed(evt);
            }
        });

        cerrarSesionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarSesionBtn.setText("Cerrar sesion");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(consultaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elimClienteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retirarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cerrarCuentaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abrirCuentaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(histTransaccionesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(contenidoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(LABEL_MENU)
                .addGap(96, 96, 96)
                .addComponent(elimClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarClienteBtn)
                .addGap(10, 10, 10)
                .addComponent(depositarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retirarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(histTransaccionesBtn)
                .addGap(64, 64, 64)
                .addComponent(cerrarSesionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abrirCuentaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarCuentaBtn)
                .addGap(38, 38, 38))
            .addComponent(contenidoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 660));

        MenuPrincipal.setAlignmentX(1.0F);
        MenuPrincipal.setAlignmentY(1.0F);

        Inicio.setText("Inicio");

        inicio_btn.setText("Volver a inicio");
        inicio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_btnActionPerformed(evt);
            }
        });
        Inicio.add(inicio_btn);

        salir_btn.setText("Salir del programa");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });
        Inicio.add(salir_btn);

        MenuPrincipal.add(Inicio);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton para volver a inicio
    private void inicio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_btnActionPerformed
        mostrarPantallaDeSesion();
    }//GEN-LAST:event_inicio_btnActionPerformed

    private void mostrarPantallaDeSesion() {
        contenidoPanel.removeAll();
        contenidoPanel.revalidate();
        contenidoPanel.repaint();

        contenidoPanel.add(inAdminBtn);
        contenidoPanel.add(InClienteBtn);
        contenidoPanel.add(registrarseBtn);
    }

    // Muestra los botones determinados en cada caso
    void ocultarBotonesDeterminados() {

        switch (modo) {
            case ADMIN -> {
                elimClienteBtn.setVisible(true);
                buscarClienteBtn.setVisible(true);
                inicio_btn.setVisible(true);
                cerrarSesionBtn.setVisible(true);
//                inicio_btn.setVisible(false);
            }
            case USER -> {
                abrirCuentaBtn.setVisible(true);
                cerrarCuentaBtn.setVisible(true);
                depositarBtn.setVisible(true);
                retirarBtn.setVisible(true);
                consultaBtn.setVisible(true);
                transBtn.setVisible(true);
                histTransaccionesBtn.setVisible(true);
                cerrarSesionBtn.setVisible(true);
                inicio_btn.setVisible(false);
            }
            case NOTHING -> {
                elimClienteBtn.setVisible(false);
                buscarClienteBtn.setVisible(false);
                abrirCuentaBtn.setVisible(false);
                cerrarCuentaBtn.setVisible(false);
                depositarBtn.setVisible(false);
                retirarBtn.setVisible(false);
                consultaBtn.setVisible(false);
                transBtn.setVisible(false);
                histTransaccionesBtn.setVisible(false);
                cerrarSesionBtn.setVisible(false);
                inicio_btn.setVisible(true);
            }
        }
    }

    // Boton para salir del programa
    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_btnActionPerformed

    // Boton para iniciar como admin
    private void inAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inAdminBtnActionPerformed
        InicioPanel p = new InicioPanel();
        modo = MODO.ADMIN;
        Tools.showPanel(p, contenidoPanel);

        ocultarBotonesDeterminados();
    }//GEN-LAST:event_inAdminBtnActionPerformed

    // Boton para mandar al menu de inicio de sesion
    private void InClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InClienteBtnActionPerformed

        AutenticarPanel p = new AutenticarPanel(this);
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_InClienteBtnActionPerformed

    // Método para actualizar el estado del Dashboard según el usuario autenticado
    public void actualizarEstado() {
        Usuario usuario = Session.getInstance().getUsuario();
        if (usuario != null) {
            setModo(MODO.USER);
        } else {
            setModo(MODO.NOTHING);
        }
        ocultarBotonesDeterminados();
    }

    void setModo(MODO modo) {
        this.modo = modo;
    }

    private void elimClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimClienteBtnActionPerformed
        ElimClientePanel p = new ElimClientePanel();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_elimClienteBtnActionPerformed

    private void buscarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteBtnActionPerformed
        BuscarClientePanel p = new BuscarClientePanel();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_buscarClienteBtnActionPerformed

    private void depositarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarBtnActionPerformed
        DepositarPNL p = new DepositarPNL();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_depositarBtnActionPerformed

    private void retirarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retirarBtnActionPerformed

    private void transBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transBtnActionPerformed

    private void consultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBtnActionPerformed
        ConsultarCuentasPanel p = new ConsultarCuentasPanel();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_consultaBtnActionPerformed

    private void abrirCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCuentaBtnActionPerformed
        AbrirCuentaPanel p = new AbrirCuentaPanel();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_abrirCuentaBtnActionPerformed

    private void cerrarCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarCuentaBtnActionPerformed

    }//GEN-LAST:event_cerrarCuentaBtnActionPerformed

    private void histTransaccionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histTransaccionesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_histTransaccionesBtnActionPerformed

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        RegistrarsePanel p = new RegistrarsePanel();
        Tools.showPanel(p, contenidoPanel);
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        Session.getInstance().cerrarSesion();
        actualizarEstado();
        mostrarPantallaDeSesion();
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InClienteBtn;
    private javax.swing.JMenu Inicio;
    private javax.swing.JLabel LABEL_MENU;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JButton abrirCuentaBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarClienteBtn;
    private javax.swing.JButton cerrarCuentaBtn;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton consultaBtn;
    private javax.swing.JPanel contenidoPanel;
    private javax.swing.JButton depositarBtn;
    private javax.swing.JButton elimClienteBtn;
    private javax.swing.JButton histTransaccionesBtn;
    private javax.swing.JButton inAdminBtn;
    private javax.swing.JMenuItem inicio_btn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton retirarBtn;
    private javax.swing.JMenuItem salir_btn;
    private javax.swing.JButton transBtn;
    // End of variables declaration//GEN-END:variables
}
