package UI;

import UI.Dashboard.MODO;
import javax.swing.JPanel;

public class MenuSesionPNL extends javax.swing.JPanel {

    Dashboard dashboard;

    public MenuSesionPNL(Dashboard dashboard) {
        this.dashboard = dashboard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InClienteBtn = new javax.swing.JButton();
        registrarseBtn = new javax.swing.JButton();
        inAdminBtn = new javax.swing.JButton();

        InClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InClienteBtn.setText("INICIAR SESION");
        InClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InClienteBtnActionPerformed(evt);
            }
        });

        registrarseBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });

        inAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inAdminBtn.setText("INICIAR COMO ADMINISTRADOR");
        inAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(363, 363, 363))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(registrarseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(InClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarseBtn)
                .addGap(224, 224, 224)
                .addComponent(inAdminBtn)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InClienteBtnActionPerformed
        AutenticacionPNL p = new AutenticacionPNL(this.dashboard);
        Tools.showPanel(p, (JPanel) this.getParent());
        dashboard.setVolverInicioBtn(true);
    }//GEN-LAST:event_InClienteBtnActionPerformed

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        RegistracionPNL p = new RegistracionPNL(this.dashboard);
        Tools.showPanel(p, (JPanel) this.getParent());
        dashboard.setVolverInicioBtn(true);
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void inAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inAdminBtnActionPerformed
        dashboard.setModo(MODO.ADMIN);
        dashboard.ocultarBotonesDeterminados();
        SesionIniciadaPNL p = new SesionIniciadaPNL();
        Tools.showPanel(p, (JPanel) this.getParent());
    }//GEN-LAST:event_inAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InClienteBtn;
    private javax.swing.JButton inAdminBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarseBtn;
    // End of variables declaration//GEN-END:variables
}
